import type { Metadata } from "next";
import "./globals.css";
import { BasicPage } from "@/app/components/basic-page/basic-page";
import { AuthProviderWrapper } from "@/app/context/auth-context";

export const metadata: Metadata = {
  title: "Wishlist App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body className="antialiased">
        <AuthProviderWrapper>
          <BasicPage>{children}</BasicPage>
        </AuthProviderWrapper>
      </body>
    </html>
  );
}
