import type { Metadata } from "next";
import "./globals.css";
import { BasicPage } from "@/components/basic-page/basic-page";

export const metadata: Metadata = {
  title: "Wishlist App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body className="antialiased">
        <BasicPage>
          {children}
        </BasicPage>
      </body>
    </html>
  );
}
